### ISSUE TITLE
Add a way to skip headers (and use string-based I/O?)

### ISSUE THREAD

**Issue by eprst** [scalameta/lsp4s#17]
There's no straightforward way to talk to LSP clients over websockets (e.g. [TypeFox/monaco-languageclient](https://github.com/TypeFox/monaco-languageclient) + [TypeFox/vscode-ws-jsonrpc](https://github.com/TypeFox/vscode-ws-jsonrpc)) as they don't support headers at the transport level.

See:
https://github.com/TypeFox/vscode-ws-jsonrpc/issues/6
https://github.com/eclipse/lsp4j/issues/189 -- similar issue in LSP4J

I think `LanguageClient/LanguageServer` should be decoupled from the transport issues and operate directly on `Observer[Json]/Observable[Json]`

**Comment by olafurpg** [comment]
Thanks for reporting! I left a comment in https://github.com/scalameta/lsp4s/pull/18#issuecomment-455811905
